:tada: php8.0
slimphp/Twig-View pull request #202
Opened 2020-12-05 21:00 UTC by jerfeson

2020-12-05 21:10 UTC, l0gicgate requested changes

2020-12-05 21:10 UTC, l0gicgate commented on Dockerfile
> +CMD [ "php" ]
Can you please remove this file?

2020-12-05 23:20 UTC, jerfeson commented on Dockerfile
> +CMD [ "php" ]
of course : )

2020-12-08 01:56 UTC, proton-ab commented
Bumping as this is blocking for us

2020-12-08 05:04 UTC, l0gicgate requested changes
We need to remove the allowed failures on the nightly builds in the `.travis.yml`

2020-12-08 09:18 UTC, seanhamlin requested changes

2020-12-08 09:18 UTC, seanhamlin commented on composer.json
> +        "php": "^7.2 | ^8.0",
Pretty sure the syntax for a logical `OR` is a double pipe. See https://getcomposer.org/doc/articles/versions.md#version-range

> You can define multiple ranges. Ranges separated by a space ( ) or comma (,) will be treated as a logical AND. A double pipe (||) will be treated as a logical OR. AND has higher precedence than OR.

```suggestion
        "php": "^7.2 || ^8.0",
```

2020-12-08 09:24 UTC, seanhamlin commented
Also by the looks TravisCI supports PHP 8.0.0 as well now https://github.com/php-build/php-build/pull/651, so it looks like you can leave `nightly` as is, and add in another PHP version to test of `8.0`.

2020-12-08 16:47 UTC, l0gicgate commented
@seanhamlin PHP 8.0 is still not working on Travis as seen here:
https://travis-ci.com/github/slimphp/Twig-View/jobs/455985200

2020-12-08 16:56 UTC, closed without merging